steps:
  - id: 'Build and push tool image'
    name: 'europe-west4-docker.pkg.dev/hmf-build/hmf-docker/docker-tag'
    args: [ 'europe-west4-docker.pkg.dev/hmf-build/hmf-docker', '$TAG_NAME', 'Dockerfile', '--cache-from', '$IMAGE_NAME:latest']

logsBucket: 'gs://hmf-build-logs'
