#!/usr/bin/env bash

sets=$1 && shift

for run in "${sets[@]}"; do
  gsutil ls "gs://diagnostic-pipeline-output-prod-1/${run}/orange/*.orange.json" "gs://oncoactin_test_data/test_cases/ver-8.0.9/${run}/input/"
  gsutil ls "gs://diagnostic-pipeline-output-prod-1/${run}/orange/*.orange.pdf" "gs://oncoactin_test_data/test_cases/ver-8.0.9/${run}/input/"
  gsutil ls "gs://diagnostic-pipeline-output-prod-1/${run}/cuppa/*.cup.report.summary.png" "gs://oncoactin_test_data/test_cases/ver-8.0.9/${run}/input/"
  gsutil ls "gs://diagnostic-pipeline-output-prod-1/${run}/purple/plot/*.circos.png" "gs://oncoactin_test_data/test_cases/ver-8.0.9/${run}/input/"
done