#!/usr/bin/env bash

source message_functions || exit 1

run=$1 && shift

lama=$(lama_get_patient_reporter_data ${isolation_barcode})
reportingId=$(echo ${lama} | jq .reportingId)
hospitalSampleLabel=$(echo ${lama} | jq .hospitalSampleLabel)
patientId=$(echo ${reportingId}-${hospitalSampleLabel} | tr -d '"')
echo -e "Isolation barcode: \033[1;32m ${isolation_barcode} \033[00m"
echo -e "Sample barcode: \033[1;32m ${tumor_sample_barcode_lowercase} \033[00m"
echo -e "Set name: \033[1;32m ${set} \033[00m"
echo -e "Patient ID: \033[1;32m ${patientId} \033[00m"