#!/usr/bin/env bash

source message_functions || exit 1

if [[ -z $1 || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Descr: Move fastq samples from fastq-input-prod-1 to hmf-crunch-innovation"
    echo " Usage: $(basename $0) submission [output folder extension]"
    echo " Exmpl: $(basename $0) HMFregINN2207 [test]"
    echo "---"
    exit 1
fi

submission_id=$1

if [[ -n $2 ]]; then
    folder_extension=$2
else
    folder_extension=$(date +%Y)
fi

info "Get samples from submission ${submission_id}"
sample_barcodes=$(hmf_api_get "samples?submission=${submission_id}" | jq -r '.[] | .barcode')

if [[ ${sample_barcodes} == "" ]]; then
    die "No samples in submission ${submission_id}"
fi

info "Copy FASTQs"
for barcode in ${sample_barcodes}; do
    destination_url="gs://hmf-crunch-innovation/fastq/HMFregINN-${folder_extension}/${submission_id}/${barcode}/"
    info "Moving sample ${barcode} from gs://fastq-input-prod-1/ to ${destination_url}"
    gsutil -m cp "gs://fastq-input-prod-1/${barcode}_*fastq.gz" "${destination_url}"
done