#!/usr/bin/env bash

source message_functions || exit 1

if [[ -z $1 || $1 == "-h" || $1 == "--help" ]]; then
    echo "---"
    echo " Descr: Move fastq samples from fastq-input-prod-1 to hmf-crunch-innovation"
    echo " Usage: $(basename $0) submission [output folder postfix]"
    echo " Exmpl: $(basename $0) HMFregINN2207"
    echo " Info: If no postfix is given the current year will be used instead"
    echo "---"
    exit 1
fi

submission_id=$1

if [[ -n $2 ]]; then
    folder_postfix=$2
else
    folder_postfix=$(date +%Y)
fi

info "Get samples from submission ${submission_id}"
sample_barcodes=$(hmf_api_get "samples?submission=${submission_id}" | jq -r '.[] | .barcode')

if [[ ${sample_barcodes} == "" ]]; then
    die "No samples in submission ${submission_id}"
fi

info "Copy FASTQs"
for barcode in ${sample_barcodes}; do
    destination_url="gs://hmf-crunch-innovation/fastq/HMFregINN-${folder_postfix}/${submission_id}/${barcode}/"
    info "Moving sample ${barcode} from gs://fastq-input-prod-1/ to ${destination_url}"
    sample_id=$(hmf_api_get "samples?barcode=${barcode}" | jq -r '.[] | .id')
    fastq_info=$(hmf_api_get "fastq?sample_id=${sample_id}")
    buckets=$(echo ${fastq_info} | jq -r '.[] | .bucket')
    names_r1=$(echo ${fastq_info} | jq -r '.[] | .name_r1')
    names_r2=$(echo ${fastq_info} | jq -r '.[] | .name_r2')
    for index in $(seq 1 $(echo "${buckets}" | wc -w));
    do
        bucket=$(echo "${buckets}" | cut -d " " -f ${index})
        name_r1=$(echo "${names_r1}" | cut -d " " -f ${index})
        name_r2=$(echo "${names_r2}" | cut -d " " -f ${index})
        gsutil -m cp "gs://${bucket}/${name_r1}" "${destination_url}"
        gsutil -m cp "gs://${bucket}/${name_r2}" "${destination_url}"
    done
done