[upload]
server_url = https://upload.test.hartwigmedicalfoundation.nl
# ONLY ADD LOCALLY, NEVER COMMIT
auth_token =

max_parallel_uploads = 6
upload_max_attempts = 3
retry_base_delay = 5
upload_timeout = 1200

[lama]
base_url = http://lama.prod-1
lama_sequencing_endpoint= api/sequencing/sequencing-run-data
lama_max_attempts = 3
http_timeout = 300

[paths]
# Where the mounted runs live and is the base folder for scanning for a new Secondary_Analysis_Complete.txt
mnt_runs_root = /usr/local/illumina/mnt/runs
# The separate root where RunParameters.xml lives.
local_runs_root = /usr/local/illumina/runs

[monitor]
poll_interval = 900

